-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 03, 2024 at 03:07 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `novinyslovakia`
--

-- --------------------------------------------------------

--
-- Table structure for table `account`
--

CREATE TABLE `account` (
  `id` int(11) NOT NULL,
  `name` varchar(155) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `account`
--

INSERT INTO `account` (`id`, `name`, `password`) VALUES
(1, 'Lamala', '$2y$10$VShNc43wQ53YzZFP6L3daO57bjnP8PstbUGvERAc9W8yPZhwsPST.');

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `headline` varchar(255) NOT NULL,
  `subhead` varchar(255) NOT NULL,
  `text` text NOT NULL,
  `img_path` varchar(255) NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp(),
  `category_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `headline`, `subhead`, `text`, `img_path`, `date`, `category_id`) VALUES
(1, 'Vplyv klimatických zmien na pobrežné mestá', 'Zvyšujúca sa hladina mora a zvyšujúce sa teploty predstavujú významné hrozby pre pobrežné regióny.', 'Klimatické zmeny sú jedným z najnaliehavejších problémov našej doby. Vedci už desaťročia varujú pred dôsledkami globálneho otepľovania a teraz začíname vidieť hmatateľné účinky. Pobrežné mestá na celom svete sú obzvlášť zraniteľné voči dopadom klimatických zmien. \r\n\r\nPodľa nedávnych štúdií sa hladina mora zvýšila približne o 20 cm od roku 1880, pričom približne 8 cm tohto nárastu sa vyskytlo za posledných 25 rokov. Toto zrýchlenie je do značnej miery spôsobené topením ľadových vrstiev a ľadovcov, ako aj tepelnou expanziou morskej vody v dôsledku jej otepľovania. \r\n\r\nOkrem zvyšovania hladiny mora zažívajú pobrežné mestá aj častejšie a intenzívnejšie poveternostné javy. Hurikány, tajfúny a iné búrky sú čoraz intenzívnejšie, čo so sebou prináša ničivé prívalové vlny a záplavy. \r\n\r\nNapríklad v roku 2012 spôsobil hurikán Sandy bezprecedentné škody v New Yorku. Prívalová vlna zaplavila metro, tunely a ulice, spôsobila miliardové škody a narušila životy miliónov ľudí. \r\n\r\nOkrem toho zvyšujúce sa teploty vedú k častejším vlnám horúčav, ktoré môžu mať vážne zdravotné dopady, najmä pre zraniteľné populácie, ako sú starší ľudia a ľudia s existujúcimi zdravotnými problémami. \r\n\r\nAby sa zmiernili tieto dopady, mestá investujú do rôznych adaptačných opatrení. Patria sem stavba morských múrov a bariér proti prívalovým vlnám, obnova mokradí a iných prírodných bariér a zavádzanie prísnejších stavebných predpisov na zabezpečenie, aby stavby odolávali extrémnym poveternostným javom. \r\n\r\nAvšak samotná adaptácia nestačí. Je tiež nevyhnutné riešiť hlavnú príčinu klimatických zmien znižovaním emisií skleníkových plynov. To si vyžaduje koordinované globálne úsilie o prechod od fosílnych palív k obnoviteľným zdrojom energie, ako sú veterná, solárna a hydroelektrická energia. \r\n\r\nJednotlivci môžu tiež zohrávať úlohu v boji proti klimatickým zmenám. Jednoduché kroky, ako je znižovanie spotreby energie, využívanie verejnej dopravy a podpora politík a iniciatív podporujúcich udržateľnosť, môžu mať významný dopad. \r\n\r\nNa záver, dopad klimatických zmien na pobrežné mestá je zložitá a mnohostranná otázka. Hoci neexistujú ľahké riešenia, kombinácia adaptačných opatrení a snáh o zníženie emisií môže pomôcť chrániť tieto zraniteľné regióny a zabezpečiť udržateľnú budúcnosť pre budúce generácie.', '/img/articles/healthwarn.jpg', '2024-06-03 00:00:00', 5),
(2, 'Technologické inovácie a ich vplyv na spoločnosť', 'Rýchly pokrok v technológiách mení spôsob, akým žijeme a pracujeme.', 'Technológie sa neustále vyvíjajú a prinášajú so sebou množstvo zmien v rôznych oblastiach nášho života. Od umelého inteligencie po kvantové počítače, tieto inovácie menia spôsob, akým žijeme, pracujeme a komunikujeme. \r\n\r\nJednou z najvýznamnejších inovácií posledných rokov je umelá inteligencia (AI). AI má potenciál revolučne zmeniť mnohé odvetvia, vrátane zdravotníctva, dopravy a výroby. S pomocou AI môžeme vytvárať inteligentné systémy, ktoré dokážu analyzovať obrovské množstvo dát a robiť presné predpovede a rozhodnutia. \r\n\r\nV zdravotníctve sa AI využíva na diagnostiku a liečbu chorôb, analýzu medicínskych obrazov a vývoj nových liekov. V doprave môžu autonómne vozidlá poháňané AI zlepšiť bezpečnosť na cestách a znížiť počet dopravných nehôd. \r\n\r\nĎalšou významnou technológiou je kvantová výpočtová technika. Kvantové počítače majú schopnosť vykonávať zložité výpočty oveľa rýchlejšie ako tradičné počítače. Tieto počítače môžu byť použité na riešenie problémov, ktoré sú pre súčasné technológie nedosiahnuteľné, ako je napríklad simulácia kvantových systémov a optimalizácia veľkých dátových súborov. \r\n\r\nTechnológie tiež menia spôsob, akým pracujeme. S rozvojom digitálnych platforiem a nástrojov môžu ľudia pracovať na diaľku a spolupracovať s kolegami po celom svete. Táto flexibilita umožňuje firmám a jednotlivcom byť produktívnejšími a efektívnejšími. \r\n\r\nAvšak rýchly technologický pokrok prináša aj výzvy. Jednou z nich je ochrana súkromia a bezpečnosti. S rastúcim množstvom dát, ktoré sú zhromažďované a analyzované, je nevyhnutné zabezpečiť, aby boli tieto dáta chránené pred zneužitím a neoprávneným prístupom. \r\n\r\nĎalšou výzvou je zmena pracovného trhu. S automatizáciou a robotizáciou môžu niektoré pracovné miesta zaniknúť, zatiaľ čo nové pracovné príležitosti vzniknú. Preto je dôležité investovať do vzdelávania a rekvalifikácie pracovníkov, aby sa mohli prispôsobiť novým technologickým požiadavkám. \r\n\r\nTechnologické inovácie prinášajú so sebou množstvo príležitostí a výziev. Je na nás, ako spoločnosti, aby sme tieto zmeny využili na zlepšenie kvality života a vytvorenie udržateľnej a prosperujúcej budúcnosti.', '/img/articles/techgiants.jpg', '2024-06-02 21:10:19', 4),
(3, 'Zdravotné riziká spojené s klimatickými zmenami', 'Zvyšujúce sa teploty a extrémne počasie ovplyvňujú zdravie ľudí.', 'Klimatické zmeny majú významný vplyv na zdravie ľudí. Zvyšujúce sa teploty a častejšie extrémne poveternostné javy, ako sú hurikány, povodne a vlny horúčav, môžu mať vážne zdravotné dôsledky. \r\n\r\nJedným z najväčších rizík spojených s klimatickými zmenami sú vlny horúčav. Vysoké teploty môžu spôsobiť úpal, dehydratáciu a zhoršiť existujúce zdravotné problémy, ako sú kardiovaskulárne ochorenia. Starší ľudia, deti a ľudia s chronickými chorobami sú obzvlášť zraniteľní. \r\n\r\nOkrem toho zvyšujúce sa teploty môžu viesť k šíreniu chorôb prenášaných komármi a kliešťami, ako sú malária, dengue a lymská borelióza. Tieto choroby sa môžu šíriť do nových oblastí, kde predtým neboli prítomné, čo predstavuje nové zdravotné riziká pre obyvateľov. \r\n\r\nExtrémne poveternostné javy, ako sú hurikány a povodne, môžu spôsobiť okamžité fyzické zranenia a úmrtia, ako aj dlhodobé zdravotné problémy. Záplavy môžu kontaminovať zdroje pitnej vody a spôsobiť šírenie infekčných chorôb. \r\n\r\nZmena klímy tiež ovplyvňuje duševné zdravie. Strach z budúcnosti, straty spôsobené prírodnými katastrofami a stres zmeny životného prostredia môžu viesť k úzkosti, depresii a posttraumatickému stresovému syndrómu. \r\n\r\nAby sme zmiernili tieto zdravotné riziká, je nevyhnutné prijať opatrenia na boj proti klimatickým zmenám. To zahŕňa znižovanie emisií skleníkových plynov, podporu obnoviteľných zdrojov energie a zlepšovanie verejného zdravia prostredníctvom vzdelávania a preventívnych opatrení. \r\n\r\nJednotlivci môžu tiež prispieť k ochrane svojho zdravia tým, že prijmú opatrenia na prispôsobenie sa zmenám klímy. To môže zahŕňať používanie klimatizácie počas vĺn horúčav, ochranu pred komármi a kliešťami a pripravenosť na prípadné prírodné katastrofy. \r\n\r\nV konečnom dôsledku je ochrana zdravia pred rizikami spojenými s klimatickými zmenami spoločnou zodpovednosťou. Spoločným úsilím môžeme zlepšiť našu pripravenosť na zmeny klímy a zabezpečiť zdravú a bezpečnú budúcnosť pre všetkých.', '/img/articles/healthwarn.jpg', '2024-06-02 21:10:19', 1),
(4, 'Udržateľný rozvoj miest: Výzvy a príležitosti', 'Rastúca urbanizácia prináša nové výzvy a príležitosti pre udržateľný rozvoj.', 'Mestá po celom svete čelia výzvam spojeným s rastúcou urbanizáciou. S rastúcim počtom obyvateľov a zvyšujúcimi sa nárokmi na infraštruktúru, dopravu a služby je nevyhnutné zabezpečiť, aby mestá rástli udržateľným spôsobom. \r\n\r\nJednou z hlavných výziev je zabezpečenie dostatočného množstva dostupného a kvalitného bývania. S rastúcim počtom obyvateľov mestá často čelia nedostatku bytov a rastúcim nákladom na bývanie. To môže viesť k zvýšeniu počtu bezdomovcov a zhoršeniu životných podmienok. \r\n\r\nDoprava je ďalšou významnou výzvou. S rastúcim počtom áut na cestách sa zvyšuje dopravné zaťaženie a znečistenie ovzdušia. Mestá musia investovať do verejnej dopravy, cyklistických trás a peších zón, aby znížili závislosť na automobiloch a podporili udržateľné spôsoby dopravy. \r\n\r\nInfraštruktúra je ďalšou kľúčovou oblasťou. Mesto musí zabezpečiť dostatočné množstvo vody, energie a ďalších základných služieb pre svojich obyvateľov. To zahŕňa investície do obnoviteľných zdrojov energie, efektívneho hospodárenia s vodou a udržateľného nakladania s odpadmi. \r\n\r\nJednou z príležitostí, ktoré prináša urbanizácia, je možnosť vytvárať inovatívne a udržateľné mestské riešenia. Mestá môžu využívať inteligentné technológie na zlepšenie efektivity dopravy, energetického manažmentu a poskytovania služieb. \r\n\r\nSpolupráca medzi verejným a súkromným sektorom je tiež dôležitá. Investície do udržateľných projektov, ako sú zelené budovy, solárne panely a mestské farmy, môžu prispieť k zlepšeniu kvality života obyvateľov a zníženiu ekologickej stopy mesta. \r\n\r\nJednotlivci môžu tiež prispieť k udržateľnosti mesta tým, že prijmú ekologické spôsoby dopravy, recyklujú odpad a podporujú lokálne iniciatívy. \r\n\r\nUdržateľný rozvoj miest je komplexná a mnohostranná otázka. Spoločným úsilím môžeme vytvárať mestá, ktoré sú nielen prosperujúce a inovatívne, ale aj ekologicky udržateľné a priateľské k svojim obyvateľom.', '/img/articles/localhero.jpeg', '2024-06-02 21:10:19', 5),
(5, 'Vzdelávanie v digitálnej ére: Výhody a výzvy', 'Technológie menia spôsob, akým sa učíme a vzdelávame.', 'Digitálna éra prináša so sebou množstvo zmien vo vzdelávaní. Technológie ako internet, počítače a mobilné zariadenia menia spôsob, akým sa učíme a prístupujeme k informáciám. \r\n\r\nJednou z hlavných výhod digitálneho vzdelávania je prístup k obrovskému množstvu informácií a zdrojov. Študenti môžu využívať online kurzy, elektronické knihy a vzdelávacie aplikácie, aby si rozšírili svoje vedomosti a zručnosti. \r\n\r\nFlexibilita je ďalšou významnou výhodou. S digitálnymi nástrojmi môžu študenti študovať kedykoľvek a kdekoľvek. To je obzvlášť užitočné pre dospelých študentov, ktorí pracujú alebo majú rodinné povinnosti. \r\n\r\nTechnológie tiež umožňujú personalizované vzdelávanie. Učitelia môžu využívať data a analytické nástroje na prispôsobenie výučby individuálnym potrebám študentov. To môže zlepšiť zapojenie a úspech študentov. \r\n\r\nAvšak digitálne vzdelávanie prináša aj výzvy. Jednou z nich je digitálna priepasť, ktorá oddeľuje tých, ktorí majú prístup k technológiám, od tých, ktorí ho nemajú. Aby bolo vzdelávanie prístupné pre všetkých, je nevyhnutné zabezpečiť, aby mali všetci študenti prístup k potrebným zariadeniam a internetovému pripojeniu. \r\n\r\nĎalšou výzvou je zabezpečenie kvality vzdelávania. S rastúcim počtom online kurzov a vzdelávacích platforiem je dôležité zabezpečiť, aby boli tieto zdroje kvalitné a relevantné. \r\n\r\nZdravotné a sociálne aspekty digitálneho vzdelávania tiež nemožno ignorovať. Dlhé hodiny strávené pred obrazovkou môžu mať negatívny dopad na zdravie očí a držanie tela. Okrem toho môže digitálne vzdelávanie obmedziť sociálne interakcie a rozvoj sociálnych zručností. \r\n\r\nPreto je dôležité nájsť rovnováhu medzi tradičným a digitálnym vzdelávaním. Kombinácia oboch prístupov môže priniesť najlepšie výsledky a zabezpečiť, aby študenti získali komplexné a kvalitné vzdelanie. \r\n\r\nV konečnom dôsledku digitálna éra prináša množstvo príležitostí na zlepšenie vzdelávania. Je na nás, aby sme tieto príležitosti využili a zabezpečili, aby bolo vzdelávanie prístupné, kvalitné a relevantné pre všetkých študentov.', '/img/articles/techgiants.jpg', '2024-06-02 21:10:19', 4),
(6, 'Ekonomické dopady pandémie COVID-19', 'Pandémia spôsobila významné zmeny v globálnej ekonomike.', 'Pandémia COVID-19 mala obrovský dopad na globálnu ekonomiku. Opatrenia na zabránenie šírenia vírusu, ako sú lockdowny, obmedzenia cestovania a zatváranie podnikov, spôsobili pokles hospodárskej aktivity a narušili dodávateľské reťazce. \r\n\r\nMnohé odvetvia, ako je cestovný ruch, pohostinstvo a maloobchod, boli obzvlášť tvrdo zasiahnuté. Zatváranie hraníc a obmedzenia pohybu viedli k drastickému poklesu počtu turistov a zákazníkov, čo malo za následok straty príjmov a hromadné prepúšťanie. \r\n\r\nVýrobný sektor tiež čelil výzvam, keďže pandémia spôsobila narušenie dodávateľských reťazcov a nedostatok surovín a komponentov. To viedlo k zníženiu výroby a oneskoreniam pri dodávkach výrobkov. \r\n\r\nMalé a stredné podniky boli obzvlášť zraniteľné. Mnohé z nich nemali dostatočné finančné rezervy na prežitie dlhodobých výpadkov a boli nútené ukončiť svoju činnosť. \r\n\r\nNa druhej strane, niektoré odvetvia zaznamenali nárast dopytu. E-commerce, zdravotníctvo a technologické firmy profitovali z rastúceho záujmu o online nákupy, zdravotnícke vybavenie a digitálne riešenia. \r\n\r\nVlády a centrálne banky na celom svete prijali rôzne opatrenia na zmiernenie ekonomických dopadov pandémie. Patrili sem fiškálne stimuly, úvery a dotácie pre podniky, znižovanie úrokových sadzieb a kvantitatívne uvoľňovanie. \r\n\r\nTieto opatrenia pomohli stabilizovať ekonomiku a podporiť obnovu, avšak priniesli aj nové výzvy, ako je rast verejného dlhu a inflačné tlaky. \r\n\r\nPandémia tiež urýchlila niektoré dlhodobé trendy, ako je digitalizácia a automatizácia. Firmy a pracovníci sa museli rýchlo prispôsobiť novým podmienkam a využiť technológie na zabezpečenie svojej činnosti. \r\n\r\nV konečnom dôsledku pandémia COVID-19 priniesla hlboké zmeny v globálnej ekonomike. Hoci niektoré z týchto zmien boli bolestivé, iné priniesli nové príležitosti a inovácie. Je dôležité, aby sme sa z týchto skúseností poučili a pripravili sa na budúce výzvy.', '/img/articles/stockmarket.jpg', '2024-06-02 21:10:19', 6),
(7, 'Význam obnoviteľných zdrojov energie', 'Obnoviteľné zdroje energie sú kľúčom k udržateľnej budúcnosti.', 'Obnoviteľné zdroje energie hrajú kľúčovú úlohu v boji proti klimatickým zmenám a zabezpečení udržateľnej budúcnosti. Využívanie slnečnej, vetrovej, vodnej a geotermálnej energie prináša množstvo výhod pre životné prostredie, ekonomiku a spoločnosť. \r\n\r\nJednou z hlavných výhod obnoviteľných zdrojov energie je, že sú nevyčerpateľné. Na rozdiel od fosílnych palív, ktoré sa časom vyčerpajú, obnoviteľné zdroje sú neustále k dispozícii. To znamená, že môžeme zabezpečiť stabilné a dlhodobé dodávky energie. \r\n\r\nObnoviteľné zdroje energie tiež produkujú minimálne emisie skleníkových plynov a ďalších znečisťujúcich látok. To prispieva k zlepšeniu kvality ovzdušia a znižovaniu negatívnych dopadov na zdravie ľudí a životné prostredie. \r\n\r\nInvestície do obnoviteľných zdrojov energie môžu tiež podporiť ekonomický rast a vytváranie nových pracovných miest. Výstavba a prevádzka solárnych a veterných elektrární, ako aj vývoj nových technológií, prinášajú pracovné príležitosti pre miestne komunity. \r\n\r\nOkrem toho obnoviteľné zdroje energie zvyšujú energetickú bezpečnosť. Závislosť od dovozu fosílnych palív môže byť riziková, najmä v prípade geopolitických konfliktov a nestability. Využívanie domácich obnoviteľných zdrojov energie znižuje túto závislosť a posilňuje nezávislosť krajiny. \r\n\r\nJednou z výziev spojených s obnoviteľnými zdrojmi energie je ich variabilita. Slnečná a veterná energia závisia od poveternostných podmienok, čo môže spôsobiť výkyvy v dodávkach energie. Riešením tohto problému sú technológie na ukladanie energie, ako sú batérie a inteligentné siete, ktoré dokážu zabezpečiť stabilné dodávky. \r\n\r\nPodpora obnoviteľných zdrojov energie vyžaduje spoluprácu medzi vládami, podnikmi a jednotlivcami. Vlády môžu vytvárať politiky a stimuly na podporu investícií do obnoviteľných zdrojov, zatiaľ čo podniky môžu vyvíjať inovatívne technológie a projekty. \r\n\r\nJednotlivci môžu tiež prispieť k podpore obnoviteľných zdrojov energie tým, že inštalujú solárne panely na svojich domoch, využívajú zelené tarify a podporujú politiky a iniciatívy na ochranu životného prostredia. \r\n\r\nV konečnom dôsledku sú obnoviteľné zdroje energie kľúčom k udržateľnej budúcnosti. Ich využívanie nám umožňuje bojovať proti klimatickým zmenám, zlepšovať kvalitu života a zabezpečiť stabilné a bezpečné dodávky energie pre budúce generácie.', '/img/articles/techgiants.jpg', '2024-06-02 21:10:19', 5),
(8, 'Zvyšovanie hladiny mora: Hrozba pre pobrežné komunity', 'Stúpajúca hladina mora ohrozuje milióny ľudí žijúcich v pobrežných oblastiach.', 'Zvyšovanie hladiny mora je jedným z najzávažnejších dôsledkov klimatických zmien. Stúpajúca hladina mora ohrozuje milióny ľudí žijúcich v pobrežných oblastiach po celom svete a prináša so sebou množstvo výziev pre mestá, komunity a životné prostredie. \r\n\r\nPodľa odhadov sa hladina mora do konca tohto storočia zvýši o 1 až 2 metre, ak nedôjde k výraznému zníženiu emisií skleníkových plynov. Tento nárast bude mať devastujúce dopady na pobrežné komunity, ktoré budú čeliť zvýšenému riziku záplav, erózie pobrežia a zhoršeniu kvality vody. \r\n\r\nZáplavy sú jedným z najväčších rizík spojených so stúpajúcou hladinou mora. Pobrežné mestá a dediny môžu byť pravidelne zaplavované, čo spôsobí škody na infraštruktúre, domoch a poľnohospodárskej pôde. To môže viesť k vysídleniu obyvateľov a zvýšeniu nákladov na obnovu a ochranu. \r\n\r\nErózia pobrežia je ďalším významným problémom. S nárastom hladiny mora sa zvyšuje aj intenzita príboja a vlnobitia, čo spôsobuje eróziu pobrežia a stratu pôdy. To môže mať negatívny dopad na ekosystémy a biodiverzitu, ako aj na ekonomické aktivity, ako je cestovný ruch a rybolov. \r\n\r\nZvyšovanie hladiny mora tiež ovplyvňuje kvalitu vody. Slaná voda môže preniknúť do sladkovodných zdrojov a kontaminovať pitnú vodu. To predstavuje zdravotné riziká pre obyvateľov a zvyšuje náklady na zabezpečenie čistej vody. \r\n\r\nAby sme zmiernili tieto dopady, je nevyhnutné prijať opatrenia na ochranu pobrežných oblastí. To zahŕňa výstavbu ochranných bariér a hrádzí, obnova mokradí a prírodných bariér, ako aj plánovanie a zónovanie, ktoré zohľadňuje riziká spojené s klimatickými zmenami. \r\n\r\nĎalšou dôležitou súčasťou riešenia je zníženie emisií skleníkových plynov. Iba znížením emisií môžeme spomaliť tempo zvyšovania hladiny mora a zmierniť jeho dopady. \r\n\r\nJednotlivci môžu tiež prispieť k ochrane pobrežných oblastí tým, že znižujú svoju ekologickú stopu, podporujú obnoviteľné zdroje energie a zapájajú sa do miestnych iniciatív na ochranu životného prostredia. \r\n\r\nV konečnom dôsledku je zvyšovanie hladiny mora globálnou výzvou, ktorá si vyžaduje spoločné úsilie. Spoluprácou môžeme chrániť pobrežné komunity, ekosystémy a zabezpečiť udržateľnú budúcnosť pre všetkých.', '/img/articles/healthwarn.jpg', '2024-06-02 21:10:19', 5),
(9, 'Význam biodiverzity pre ekosystémy a ľudstvo', 'Biodiverzita je kľúčovým faktorom pre zdravie a stabilitu ekosystémov.', 'Biodiverzita, alebo biologická diverzita, označuje rozmanitosť života na Zemi. Zahŕňa rôzne druhy rastlín, živočíchov a mikroorganizmov, ako aj genetickú diverzitu v rámci jednotlivých druhov a ekosystémov. Biodiverzita je kľúčovým faktorom pre zdravie a stabilitu ekosystémov a má veľký význam pre ľudstvo. \r\n\r\nJednou z hlavných výhod biodiverzity je jej prínos pre ekosystémové služby. Ekosystémy poskytujú množstvo služieb, ktoré sú nevyhnutné pre život na Zemi, vrátane čistenia vzduchu a vody, opelenia plodín, regulácie klímy a ochrany pred prírodnými katastrofami. Vysoká biodiverzita zvyšuje odolnosť ekosystémov voči zmenám a stresom, čo znamená, že sú schopné lepšie sa prispôsobiť a obnoviť po narušení. \r\n\r\nBiodiverzita tiež poskytuje zdroje pre ľudskú výživu a zdravie. Mnohé lieky a liečivá pochádzajú z rastlín a živočíchov, ktoré sú súčasťou biodiverzity. Okrem toho biodiverzita prispieva k rozmanitosti potravinových zdrojov, čo zvyšuje bezpečnosť potravín a znižuje riziko hladomorov. \r\n\r\nEkonomický prínos biodiverzity je tiež významný. Cestovný ruch a rekreačné aktivity, ako je ekoturizmus, rybolov a poľovníctvo, závisia od zdravých a rozmanitých ekosystémov. Ochrana biodiverzity môže podporiť udržateľný hospodársky rast a vytváranie pracovných miest. \r\n\r\nBiodiverzita má tiež kultúrny a estetický význam. Mnohé kultúry a spoločnosti čerpajú inšpiráciu a duchovné hodnoty z prírody a jej rozmanitosti. Ochrana biodiverzity prispieva k zachovaniu kultúrneho dedičstva a zvyšuje kvalitu života. \r\n\r\nNapriek jej významu čelí biodiverzita mnohým hrozbám, vrátane straty biotopov, znečistenia, klimatických zmien a invazívnych druhov. Ochrana biodiverzity vyžaduje koordinované úsilie na miestnej, národnej a globálnej úrovni. \r\n\r\nJednotlivci môžu tiež prispieť k ochrane biodiverzity tým, že podporujú ochranu prírody, znižujú svoju ekologickú stopu a zapájajú sa do miestnych iniciatív na ochranu životného prostredia. \r\n\r\nV konečnom dôsledku je biodiverzita kľúčovým faktorom pre zdravie a stabilitu ekosystémov a má veľký význam pre ľudstvo. Je našou zodpovednosťou chrániť a zachovávať biodiverzitu pre budúce generácie.', '/img/articles/localhero.jpeg', '2024-06-02 21:10:19', 5),
(10, 'Inovácie v zdravotníctve: Budúcnosť medicíny', 'Technologický pokrok prináša revolučné zmeny v zdravotníctve.', 'Technologický pokrok prináša revolučné zmeny v zdravotníctve a otvára nové možnosti pre diagnostiku, liečbu a prevenciu chorôb. Od umelého inteligencie po biotechnológie, inovácie v medicíne menia spôsob, akým poskytujeme zdravotnú starostlivosť. \r\n\r\nJednou z najvýznamnejších inovácií je umelá inteligencia (AI). AI má potenciál zlepšiť diagnostiku a liečbu chorôb tým, že analyzuje obrovské množstvo dát a identifikuje vzory, ktoré môžu byť pre ľudských lekárov neviditeľné. AI môže tiež pomôcť pri predpovedaní vývoja chorôb a personalizácii liečby na základe individuálnych charakteristík pacienta. \r\n\r\nBiotechnológie sú ďalšou oblasťou, kde prebieha významný pokrok. Genetické inžinierstvo a terapia génmi umožňujú liečbu genetických chorôb, ktoré boli kedysi neliečiteľné. Výskum kmeňových buniek otvára nové možnosti pre regeneratívnu medicínu a liečbu zranení a degeneratívnych chorôb. \r\n\r\nTelemedicína je ďalšou inováciou, ktorá mení spôsob, akým poskytujeme zdravotnú starostlivosť. Vďaka digitálnym technológiám môžu pacienti konzultovať so svojimi lekármi na diaľku, čo zvyšuje prístup k zdravotnej starostlivosti a znižuje náklady na dopravu a čakacie doby. \r\n\r\nNositeľné zariadenia, ako sú inteligentné hodinky a fitnes trackery, umožňujú monitorovať zdravotný stav v reálnom čase. Tieto zariadenia môžu sledovať srdcovú frekvenciu, úroveň aktivity, spánok a ďalšie zdravotné parametre, čo umožňuje včasné odhalenie zdravotných problémov a prevenciu chorôb. \r\n\r\nAvšak s týmito inováciami prichádzajú aj výzvy. Jednou z nich je ochrana súkromia a bezpečnosti dát. S rastúcim množstvom zdravotných dát je nevyhnutné zabezpečiť, aby boli tieto dáta chránené pred neoprávneným prístupom a zneužitím. \r\n\r\nĎalšou výzvou je zabezpečenie rovnakého prístupu k inovatívnym liečbam a technológiám. Je dôležité, aby všetci pacienti mali možnosť využívať výhody technologického pokroku bez ohľadu na ich finančnú situáciu alebo miesto bydliska. \r\n\r\nV konečnom dôsledku inovácie v zdravotníctve prinášajú množstvo príležitostí na zlepšenie kvality života a zdravia ľudí. Je na nás, aby sme tieto príležitosti využili a zabezpečili, aby boli nové technológie a liečby prístupné a bezpečné pre všetkých.', '/img/articles/techgiants.jpg', '2024-06-02 21:10:19', 1),
(45, 'Nový prelom vo výskume rakoviny prináša nádej pre pacientov', 'Vedci dosiahli významný pokrok vo vývoji novej liečby rakoviny, ktorá by mohla zmeniť budúcnosť onkologickej medicíny.', 'Vedci z celého sveta pracujú na nových liečebných postupoch, ktoré by mohli výrazne zlepšiť prognózu pacientov s rôznymi typmi rakoviny. Tento nový výskum prináša sľubné výsledky a môže otvoriť dvere k novým možnostiam liečby. Medzi najnovšie objavy patrí identifikácia konkrétnych génov, ktoré zohrávajú kľúčovú úlohu v rozvoji rakoviny, a vývoj liekov, ktoré cielia priamo na tieto gény. Vedci veria, že s ďalším výskumom a klinickými skúškami by mohli tieto lieky výrazne zlepšiť prežitie a kvalitu života pacientov s rakovinou. Okrem toho sa skúmajú aj nové spôsoby imunoterapie, ktoré by mohli pomôcť telu bojovať proti rakovine prirodzenejším spôsobom. Tieto prelomové metódy liečby môžu priniesť nádej tisícom pacientov, ktorí čelia tejto zákernej chorobe.', '/img/articles/health1.jpg', '2024-06-03 00:01:00', 1),
(46, 'Výhody rastlinnej stravy: Ako môže zlepšiť vaše zdravie a predĺžiť život', 'Výskumy ukazujú, že rastlinná strava môže výrazne zlepšiť celkové zdravie a znížiť riziko chronických ochorení.', 'Prechod na rastlinnú stravu môže priniesť množstvo zdravotných výhod vrátane zníženia rizika srdcových chorôb, cukrovky a niektorých typov rakoviny. Táto strava je bohatá na vitamíny, minerály a antioxidanty, ktoré podporujú zdravie. Štúdie ukazujú, že ľudia, ktorí dodržiavajú rastlinnú stravu, majú nižšie hladiny cholesterolu a krvného tlaku a sú menej náchylní na obezitu. Okrem toho, rastlinná strava môže podporiť trávenie a znížiť zápal v tele, čo môže prispieť k lepšiemu fyzickému a duševnému zdraviu. Výskumy tiež naznačujú, že rastlinná strava môže predĺžiť životnosť a zlepšiť kvalitu života tým, že poskytuje telu potrebné živiny bez nadmerného množstva nasýtených tukov a cukrov. Pre mnohých ľudí je prechod na rastlinnú stravu aj spôsobom, ako prispieť k ochrane životného prostredia a zníženiu ekologickej stopy.', '/img/articles/health2.jpg', '2024-06-03 00:01:00', 1),
(47, 'Ako zlepšiť duševné zdravie: Rady od odborníkov na zvládanie stresu a zlepšenie psychickej pohody', 'Odborníci zdieľajú tipy na to, ako zvládať stres a zlepšiť duševnú pohodu pomocou jednoduchých techník a zmien v životnom štýle.', 'Zlepšenie duševného zdravia môže byť dosiahnuté rôznymi spôsobmi, vrátane pravidelného cvičenia, meditácie a správneho spánkového režimu. Odborníci tiež odporúčajú praktiky ako mindfulness a pravidelné socializovanie sa s priateľmi a rodinou. Pravidelné fyzické aktivity, ako je jogging, jóga alebo plávanie, môžu pomôcť znižovať hladinu stresu a zlepšovať náladu. Meditácia a mindfulness techniky môžu pomôcť zlepšiť koncentráciu a zvládať negatívne myšlienky. Správny spánkový režim a vyvážená strava sú tiež kľúčovými faktormi pre udržanie dobrej psychickej pohody. Ďalším dôležitým aspektom je hľadanie rovnováhy medzi pracovným a osobným životom, čo môže zahŕňať plánovanie času na relaxáciu, záľuby a aktivity, ktoré prinášajú radosť a uspokojenie.', '/img/articles/health3.png', '2024-06-03 00:01:00', 1),
(48, 'Dôležitosť spánku pre zdravie: Nové štúdie odhaľujú kľúčové fakty', 'Nová štúdia zdôrazňuje význam spánku pre udržanie dobrého zdravia a prevenciu chorôb, ktoré môžu vzniknúť z nedostatku spánku.', 'Spánok hrá kľúčovú úlohu v našom zdraví a pohode. Nedostatok spánku môže viesť k rôznym zdravotným problémom vrátane obezity, srdcových chorôb a depresie. Nové štúdie ukazujú, že kvalitný spánok je nevyhnutný pre regeneráciu tela a mozgu. Počas spánku dochádza k oprave buniek, posilneniu imunitného systému a zlepšeniu pamäte. Odborníci odporúčajú, aby dospelí spali aspoň 7-8 hodín denne a vytvárali si pravidelné spánkové návyky, ako je chodenie spať a vstávanie v rovnaký čas každý deň. Je tiež dôležité vytvoriť si príjemné prostredie na spánok, čo môže zahŕňať tmavú a tichú miestnosť, pohodlný matrac a vyhýbanie sa elektronickým zariadeniam pred spaním. Tieto opatrenia môžu výrazne zlepšiť kvalitu spánku a tým aj celkovú pohodu.', '/img/articles/health4.jpg', '2024-06-03 00:01:00', 1),
(49, 'Vzostup telemedicíny: Ako digitálne technológie menia zdravotnú starostlivosť', 'Telemedicína sa stáva stále populárnejšou vďaka svojej schopnosti poskytovať zdravotnú starostlivosť na diaľku a zlepšovať prístup k lekárskym službám.', 'Telemedicína umožňuje pacientom konzultovať s lekármi cez internet, čo je výhodné najmä pre ľudí žijúcich v odľahlých oblastiach. Táto technológia prináša revolúciu v zdravotnej starostlivosti, umožňuje rýchlejší prístup k odborníkom a šetrí čas aj peniaze. Pacienti môžu jednoducho naplánovať konzultácie, získať recepty a sledovať svoje zdravotné záznamy online. Telemedicína tiež umožňuje lekárom monitorovať pacientov na diaľku, čo môže byť obzvlášť užitočné pre chronických pacientov a starších ľudí. Vďaka pokročilým technológiám, ako sú videohovory, digitálne zdravotné záznamy a nositeľné zariadenia, môžu lekári poskytovať vysokokvalitnú starostlivosť bez potreby fyzickej prítomnosti pacienta v ordinácii. Táto forma zdravotnej starostlivosti sa ukázala byť mimoriadne účinná počas pandémie COVID-19, keď bolo potrebné minimalizovať osobné kontakty.', '/img/articles/health1.jpg', '2024-06-03 00:01:00', 1),
(50, 'Zdravie a výživa: Aký vplyv má strava na vaše telo a myseľ', 'Odborníci na výživu vysvetľujú, ako rôzne potraviny môžu ovplyvniť fyzické a duševné zdravie a poskytujú rady, ako si vytvoriť zdravší jedálniček.', 'Strava má priamy vplyv na naše zdravie a pohodu. Správne zvolené potraviny môžu posilniť imunitný systém, zlepšiť náladu a zvýšiť energiu. Odborníci odporúčajú zamerať sa na vyváženú stravu bohatú na ovocie, zeleninu, celozrnné produkty a zdravé tuky. Potraviny ako avokádo, orechy, semená a ryby bohaté na omega-3 mastné kyseliny môžu podporovať zdravie mozgu a srdca. Je tiež dôležité obmedziť príjem spracovaných potravín, cukru a nasýtených tukov, ktoré môžu prispievať k zápalom a rôznym zdravotným problémom. Správna výživa tiež hrá kľúčovú úlohu v prevencii a liečbe mnohých ochorení, vrátane obezity, cukrovky a srdcových chorôb. Vyvážená strava môže pomôcť udržiavať stabilnú hladinu energie počas dňa, zlepšiť koncentráciu a podporiť celkovú psychickú pohodu.', '/img/articles/health5.jpg', '2024-06-03 00:01:00', 1),
(51, 'Zlatan Ibrahimović oznamuje koniec svojej kariéry', 'Legendárny futbalista Zlatan Ibrahimović oznámil, že po dlhoročnej kariére plnej úspechov končí s profesionálnym futbalom.', 'Zlatan Ibrahimović, jeden z najväčších futbalistov všetkých čias, oznámil, že končí svoju profesionálnu kariéru. Počas svojej kariéry hral za niekoľko prestížnych klubov vrátane Ajaxu, Juventusu, Interu Miláno, Barcelony, Paríža Saint-Germain a Manchestru United. Zlatan bol známy svojou fyzickou silou, technickými schopnosťami a nezlomným duchom. Počas svojej kariéry získal množstvo trofejí a individuálnych ocenení. Jeho odchod je veľkou stratou pre futbalový svet, ale Zlatan sľubuje, že bude pokračovať v prínose k športu v iných formách.', 'https://placehold.co/600x400', '2024-06-03 00:03:11', 2),
(52, 'Olympijské hry v Tokiu: Slovenskí športovci získali rekordný počet medailí', 'Slovenskí športovci dosiahli historický úspech na olympijských hrách v Tokiu, keď získali rekordný počet medailí.', 'Slovenskí športovci dosiahli na olympijských hrách v Tokiu veľký úspech, keď získali rekordný počet medailí. Medzi najvýraznejšie úspechy patrí zlatá medaila v kanoistike, strieborná medaila v streľbe a bronzová medaila v atletike. Tieto úspechy sú výsledkom tvrdej práce, odhodlania a podpory celého tímu. Slovensko sa na olympijských hrách predstavilo vo viacerých športových disciplínach a športovci preukázali vysokú úroveň pripravenosti a talentu. Tento historický úspech je veľkým povzbudením pre budúce generácie slovenských športovcov a ukazuje, že aj malá krajina môže dosiahnuť veľké veci na medzinárodnej scéne.', '/img/articles/sport6.jpg', '2024-06-03 00:03:11', 2),
(53, 'Futbalový svet šokovaný odchodom Lionela Messiho z Barcelony', 'Lionel Messi oznámil svoj odchod z FC Barcelona po viac ako dvoch dekádach strávených v tomto klube, čím šokoval celý futbalový svet.', 'Lionel Messi, jeden z najlepších futbalistov všetkých čias, oznámil svoj odchod z FC Barcelona. Tento krok šokoval celý futbalový svet, pretože Messi strávil v tomto klube viac ako dve desaťročia a stal sa jeho ikonou. Počas svojej kariéry v Barcelone získal množstvo trofejí vrátane viacerých titulov v La Lige a Ligy majstrov. Messiho odchod je spojený s finančnými problémami klubu a neschopnosťou splniť požiadavky na jeho nový kontrakt. Fanúšikovia Barcelony sú sklamaní, ale Messi už naznačil, že bude pokračovať v kariére v inom prestížnom klube, kde bude mať možnosť pridať ďalšie úspechy do svojej bohaté kariéry.', '/img/articles/sport5.jpg', '2024-06-03 00:03:11', 2),
(54, 'Návrat boxu: Mike Tyson sa pripravuje na nový zápas', 'Legendárny boxer Mike Tyson oznámil svoj návrat do ringu a pripravuje sa na nový zápas proti bývalému rivalovi.', 'Mike Tyson, jeden z najznámejších boxerov všetkých čias, oznámil svoj návrat do ringu. Tyson, ktorý je známy svojou nekompromisnou silou a agresívnym štýlom, sa pripravuje na nový zápas proti svojmu bývalému rivalovi. Tento zápas bude sledovať milióny fanúšikov po celom svete. Tysonov návrat je veľkým lákadlom pre boxerskú komunitu, pretože predstavuje príležitosť vidieť v akcii jedného z najdominantnejších boxerov v histórii. Tyson sľubuje, že je vo výbornej forme a pripravený predviesť svoju najlepšiu výkonnosť. Tento zápas bude určite nezabudnuteľnou udalosťou v histórii boxu.', '/img/articles/sport4.jpg', '2024-06-03 00:03:11', 2),
(55, 'Tour de France: Peter Sagan sa pripravuje na ďalší pokus o zelený dres', 'Slovenský cyklista Peter Sagan sa opäť pripravuje na Tour de France, kde bude bojovať o svoj ďalší zelený dres pre najlepšieho šprintéra.', 'Peter Sagan, jeden z najúspešnejších slovenských cyklistov, sa opäť pripravuje na Tour de France. Sagan, ktorý je známy svojimi šprintérskymi schopnosťami, bude bojovať o svoj ďalší zelený dres pre najlepšieho šprintéra. Tour de France je jedným z najprestížnejších cyklistických pretekov na svete a Sagan má na tomto podujatí bohatú históriu úspechov. Jeho príprava zahŕňa intenzívny tréning, zlepšovanie techniky a strategické plánovanie. Sagan verí, že je pripravený na výzvy, ktoré Tour de France prináša, a že opäť ukáže svoju dominanciu v šprintérskych etapách. Fanúšikovia cyklistiky sa už tešia na jeho výkony a dúfajú, že pridá ďalší úspech do svojej už tak bohatej kariéry.', '/img/articles/sport3.jpg', '2024-06-03 00:03:11', 2),
(56, 'Nová hviezda NBA: Luka Dončić sa stáva ikonou basketbalu', 'Mladý slovinský basketbalista Luka Dončić sa rýchlo stáva jednou z najväčších hviezd NBA a zarába si rešpekt svojimi neuveriteľnými výkonmi na ihrisku.', 'Luka Dončić, mladý a talentovaný slovinský basketbalista, sa rýchlo stáva jednou z najväčších hviezd NBA. Dončić, ktorý začal svoju kariéru v Európe, vstúpil do NBA s veľkými očakávaniami a rýchlo ich prekonal svojimi neuveriteľnými výkonmi na ihrisku. Jeho schopnosť skórovať, asistovať a dominovať v zápasoch mu priniesla rešpekt a obdiv po celom svete. Dončić je známy svojou pracovnou etikou, basketbalovou inteligenciou a schopnosťou viesť svoj tím k víťazstvám. S každým zápasom sa zlepšuje a ukazuje, že má potenciál stať sa jedným z najlepších hráčov v histórii NBA. Jeho budúcnosť v basketbale vyzerá veľmi sľubne a fanúšikovia sa už tešia na jeho ďalšie úspechy.', '/img/articles/sport2.jpg', '2024-06-03 00:03:11', 2),
(57, 'Prezident oznamuje nové ekonomické reformy na podporu rastu', 'Prezident predstavil súbor nových ekonomických reforiem zameraných na podporu hospodárskeho rastu a zlepšenie životnej úrovne obyvateľov.', 'Prezident dnes oznámil ambiciózny súbor ekonomických reforiem, ktoré majú za cieľ stimulovať hospodársky rast a zlepšiť životnú úroveň občanov. Medzi hlavné body reformy patrí znižovanie daní pre malé a stredné podniky, zvyšovanie investícií do infraštruktúry a vzdelávania, ako aj podpora inovácií a technologického rozvoja. Prezident zdôraznil, že tieto opatrenia sú nevyhnutné na to, aby krajina mohla čeliť globálnym ekonomickým výzvam a zabezpečila udržateľný rast v budúcnosti. Reformy sú navrhnuté tak, aby podporovali tvorbu nových pracovných miest a znižovali sociálne nerovnosti. Prezident vyzval všetky politické strany na spoluprácu a podporu týchto kľúčových opatrení.', 'https://placehold.co/600x400', '2024-06-03 00:13:01', 3),
(58, 'Parlament schválil nový zákon na ochranu životného prostredia', 'Nový zákon na ochranu životného prostredia, ktorý bol dnes schválený parlamentom, zavádza prísnejšie regulácie na zníženie znečistenia a ochranu prírodných zdrojov.', 'Parlament dnes schválil nový zákon na ochranu životného prostredia, ktorý zavádza prísnejšie regulácie na zníženie znečistenia a ochranu prírodných zdrojov. Tento zákon je považovaný za jeden z najambicióznejších environmentálnych opatrení, aké kedy boli prijaté. Zahŕňa opatrenia na znižovanie emisií skleníkových plynov, ochranu vodných zdrojov a lesov, ako aj podporu obnoviteľných zdrojov energie. Minister životného prostredia uviedol, že tento zákon je kľúčovým krokom v boji proti klimatickým zmenám a zabezpečí, že budúce generácie budú môcť žiť v zdravom a udržateľnom prostredí. Zákon tiež obsahuje finančné stimuly pre podniky, ktoré prijmú ekologické technológie a postupy.', 'https://placehold.co/600x400', '2024-06-03 00:13:01', 3),
(59, 'Medzinárodný summit: Lídri diskutujú o globálnych bezpečnostných hrozbách', 'Lídri z celého sveta sa stretli na medzinárodnom summite, aby diskutovali o súčasných globálnych bezpečnostných hrozbách a hľadali spôsoby, ako im čeliť.', 'Lídri z celého sveta sa tento týždeň stretli na medzinárodnom summite, kde diskutovali o súčasných globálnych bezpečnostných hrozbách a hľadali spôsoby, ako im čeliť. Medzi hlavné témy patrili terorizmus, kybernetická bezpečnosť, klimatické zmeny a geopolitické napätie. Prezident hostiteľskej krajiny zdôraznil, že medzinárodná spolupráca je kľúčová pre riešenie týchto výziev a vyzval na jednotu a solidaritu medzi národmi. Summit priniesol množstvo návrhov a iniciatív, vrátane vytvorenia nových medzinárodných aliancií a posilnenia existujúcich bezpečnostných opatrení. Lídri sa zhodli na tom, že je potrebné investovať viac do prevencie konfliktov a budovania mieru.', 'https://placehold.co/600x400', '2024-06-03 00:13:01', 3),
(60, 'Voľby v krajine: Politické strany bojujú o hlasy voličov', 'Blížiace sa voľby vyvolávajú intenzívnu kampaň, v ktorej politické strany bojujú o hlasy voličov rôznymi stratégiami a sľubmi.', 'Blížiace sa voľby v krajine vyvolávajú intenzívnu kampaň, v ktorej politické strany bojujú o hlasy voličov rôznymi stratégiami a sľubmi. Každá strana predstavuje svoje programy zamerané na riešenie kľúčových problémov, ako sú ekonomický rast, zdravotná starostlivosť, vzdelávanie a bezpečnosť. Kandidáti organizujú mítingy, diskusie a mediálne vystúpenia, aby presvedčili voličov o svojej vízii pre budúcnosť krajiny. Analytici predpovedajú tesný súboj medzi hlavnými stranami, pričom výsledok môže byť ovplyvnený mnohými faktormi, vrátane účasti mladých voličov a ekonomických podmienok. Voľby budú mať zásadný vplyv na smerovanie krajiny v nasledujúcich rokoch.', '/img/articles/politika5.jpg', '2024-06-03 00:13:01', 3),
(61, 'Reforma školstva: Vláda predstavuje nový plán na zlepšenie vzdelávania', 'Vláda dnes predstavila ambiciózny plán na reformu školstva, ktorý má za cieľ zlepšiť kvalitu vzdelávania a pripraviť študentov na výzvy 21. storočia.', 'Vláda dnes predstavila ambiciózny plán na reformu školstva, ktorý má za cieľ zlepšiť kvalitu vzdelávania a pripraviť študentov na výzvy 21. storočia. Plán zahŕňa investície do infraštruktúry škôl, modernizáciu učebných osnov a zlepšenie podmienok pre učiteľov. Minister školstva uviedol, že cieľom reformy je vytvoriť vzdelávací systém, ktorý bude podporovať kritické myslenie, tvorivosť a inovatívnosť. Reforma tiež zahŕňa zvýšenie financovania pre výskum a vývoj, ako aj rozšírenie programov celoživotného vzdelávania. Vláda vyzvala všetky zainteresované strany, vrátane učiteľov, rodičov a študentov, aby podporili tento plán a prispeli k jeho úspešnej realizácii.', '/img/articles/politika4.jpg', '2024-06-03 00:13:01', 3),
(62, 'Diskusia o migrácii: Európske krajiny hľadajú spoločné riešenia', 'Lídri európskych krajín sa stretli na summite, aby diskutovali o problémoch migrácie a hľadali spoločné riešenia na zvládnutie migračných tokov.', 'Lídri európskych krajín sa tento týždeň stretli na summite, kde diskutovali o problémoch migrácie a hľadali spoločné riešenia na zvládnutie migračných tokov. Téma migrácie je už dlhodobo jedným z najkontroverznejších a najdiskutovanejších problémov v Európe. Na summite boli predstavené rôzne návrhy vrátane posilnenia hraníc, zvýšenia finančnej podpory pre krajiny najviac postihnuté migráciou a vytvorenia nových programov na integráciu migrantov. Lídri sa zhodli na tom, že je potrebné nájsť vyvážený prístup, ktorý zabezpečí bezpečnosť a stabilitu, zároveň však rešpektuje ľudské práva a medzinárodné záväzky. Diskusia tiež zahŕňala témy ako boj proti pašovaniu ľudí a zlepšenie podmienok v krajinách pôvodu migrantov.', '/img/articles/politika3.jpg', '2024-06-03 00:13:01', 3),
(63, 'Nová generácia smartfónov prináša revolučné technológie', 'Výrobcovia predstavili najnovšie modely smartfónov, ktoré sú vybavené revolučnými technológiami a inováciami.', 'Technologické spoločnosti nedávno predstavili najnovšie modely smartfónov, ktoré prinášajú množstvo revolučných technológií a inovácií. Medzi najvýraznejšie novinky patrí pokročilá umelá inteligencia, ktorá umožňuje lepšiu personalizáciu používateľského zážitku, a nové senzory, ktoré zlepšujú kvalitu fotografií a videí. Nové smartfóny sú tiež vybavené rýchlejšími procesormi a väčšou pamäťou, čo zaručuje plynulý chod aj pri náročných aplikáciách. Výrobcovia tiež kladú dôraz na ekologické aspekty a použitie recyklovaných materiálov. Táto nová generácia smartfónov predstavuje významný krok vpred a ukazuje smer, akým sa bude tento segment v budúcnosti uberať.', 'https://placehold.co/600x400', '2024-06-03 00:20:04', 4),
(64, 'Virtuálna realita: Ako mení herný priemysel a ďalšie odvetvia', 'Virtuálna realita sa stáva čoraz populárnejšou a mení spôsob, akým hráme hry, vzdelávame sa a komunikujeme.', 'Virtuálna realita (VR) zažíva veľký boom a mení spôsob, akým vnímame svet okolo nás. V hernom priemysle umožňuje hráčom ponoriť sa do úplne nových a interaktívnych svetov. VR však nachádza uplatnenie aj v mnohých ďalších odvetviach, ako je vzdelávanie, zdravotníctvo a architektúra. V školách môže VR pomôcť študentom lepšie pochopiť komplexné koncepty tým, že ich vizualizuje v 3D priestore. V zdravotníctve sa používa na simuláciu chirurgických zákrokov a na tréning lekárov. Architekti môžu pomocou VR vytvárať realistické modely budov a prostredí, čo umožňuje lepšiu predstavu o konečnom výsledku. Táto technológia má obrovský potenciál a už teraz mení spôsob, akým žijeme a pracujeme.', 'https://placehold.co/600x400', '2024-06-03 00:20:04', 4),
(65, 'Vývoj umelej inteligencie: Príležitosti a výzvy', 'Umelej inteligencie (AI) sa stáva neoddeliteľnou súčasťou našich životov, prináša nové príležitosti, ale aj výzvy.', 'Umelej inteligencie (AI) je jedným z najrýchlejšie sa rozvíjajúcich odvetví technológie. Jej aplikácie nájdeme v rôznych oblastiach, od zdravotníctva cez dopravu až po financie. AI dokáže analyzovať veľké množstvo dát a poskytovať presné predpovede, čo prináša nové možnosti pre optimalizáciu procesov a zlepšenie služieb. Na druhej strane však AI prináša aj výzvy, ako je ochrana súkromia a bezpečnosť dát. Existuje tiež obava, že AI môže viesť k zániku niektorých pracovných miest. Vývojári a regulátori musia spolupracovať na vytváraní etických noriem a zabezpečení, že AI bude slúžiť ľuďom a nie naopak. Práca na týchto otázkach je kľúčová pre zabezpečenie udržateľného a zodpovedného rozvoja AI.', 'https://placehold.co/600x400', '2024-06-03 00:20:04', 4),
(66, 'Internet vecí (IoT): Ako prepojené zariadenia menia náš každodenný život', 'Internet vecí (IoT) prináša revolúciu v našom každodennom živote tým, že prepája rôzne zariadenia a umožňuje ich inteligentné riadenie.', 'Internet vecí (IoT) je technológia, ktorá umožňuje prepojenie rôznych zariadení cez internet, čo prináša nové možnosti pre domácnosti, firmy aj mestá. V domácnostiach môžeme pomocou IoT riadiť osvetlenie, kúrenie, bezpečnostné systémy a dokonca aj spotrebiče, ako sú chladničky a práčky. Firmy využívajú IoT na monitorovanie výrobných procesov, správu zásob a zlepšenie efektivity. V mestách sa IoT používa na správu dopravy, verejného osvetlenia a odpadového hospodárstva, čo zlepšuje kvalitu života obyvateľov. IoT tiež prináša nové výzvy v oblasti bezpečnosti a ochrany súkromia, pretože prepojené zariadenia môžu byť cieľom kybernetických útokov. Je dôležité, aby vývojári a používatelia venovali pozornosť týmto otázkam a zabezpečili bezpečné a spoľahlivé používanie IoT technológií.', '/img/articles/techno5.jpg', '2024-06-03 00:20:04', 4),
(67, 'Kybernetická bezpečnosť: Ako sa chrániť pred hrozbami v digitálnom svete', 'Kybernetická bezpečnosť je dnes dôležitejšia ako kedykoľvek predtým, pretože hrozby v digitálnom svete stále rastú.', 'V digitálnom svete, kde je stále viac našich aktivít a informácií prenášaných cez internet, je kybernetická bezpečnosť kľúčová. Hackeri a kyberzločinci neustále hľadajú nové spôsoby, ako získať prístup k citlivým údajom a narušiť systémy. Preto je dôležité, aby jednotlivci aj organizácie prijali opatrenia na ochranu svojich digitálnych aktív. Medzi základné kroky patrí používanie silných a unikátnych hesiel, pravidelné aktualizácie softvéru, používanie antivírusových programov a bezpečnostných riešení. Organizácie by mali investovať do školení svojich zamestnancov, aby boli oboznámení s najnovšími hrozbami a vedeli, ako sa proti nim brániť. Kybernetická bezpečnosť je dynamická a neustále sa meniaca oblasť, preto je dôležité byť vždy o krok pred útočníkmi a chrániť svoje údaje a systémy.', '/img/articles/techno4.jpg', '2024-06-03 00:20:04', 4),
(68, 'Blockchain technológia: Potenciál a budúcnosť decentralizovaných systémov', 'Blockchain technológia prináša nové možnosti pre decentralizované systémy a má potenciál zmeniť rôzne odvetvia.', 'Blockchain je technológia, ktorá umožňuje vytváranie decentralizovaných a transparentných systémov, kde všetky transakcie sú zaznamenané v distribuovanej databáze. Táto technológia je základom pre kryptomeny, ako je Bitcoin, ale jej potenciál siaha oveľa ďalej. Blockchain môže zmeniť rôzne odvetvia, vrátane finančných služieb, logistiky, zdravotníctva a verejnej správy. Vďaka svojej schopnosti zabezpečiť transparentnosť a nezmeniteľnosť záznamov môže blockchain pomôcť znížiť podvody, zlepšiť sledovateľnosť produktov a zefektívniť administratívne procesy. Napriek tomu, že blockchain má veľký potenciál, čelí aj výzvam, ako je škálovateľnosť a regulácia. Vývojári a regulátori musia spolupracovať na tom, aby zabezpečili, že táto technológia bude používaná zodpovedne a prinášala výhody pre celú spoločnosť.', '/img/articles/techno3.jpg', '2024-06-03 00:20:04', 4),
(69, 'Klimatické zmeny a ich dopad na biodiverzitu: Výzvy a riešenia', 'Klimatické zmeny výrazne ovplyvňujú biodiverzitu na Zemi, ohrozujú mnohé druhy a ekosystémy.', 'Klimatické zmeny majú významný vplyv na biodiverzitu, spôsobujú zmeny v distribúcii druhov a ich životných prostrediach. Zvýšenie teplôt, zmeny v zrážkových vzorcoch a extrémne poveternostné udalosti nútia mnohé druhy adaptovať sa alebo migrovať do nových oblastí. Niektoré druhy, ktoré nie sú schopné sa prispôsobiť rýchlym zmenám, čelia vyhynutiu. Ochrana biodiverzity vyžaduje komplexný prístup, ktorý zahŕňa zníženie emisií skleníkových plynov, ochranu prírodných rezervácií a implementáciu udržateľných hospodárskych praktík. Medzinárodná spolupráca je kľúčová na riešenie týchto výziev a zabezpečenie, že budúce generácie budú môcť žiť v ekosystémoch bohatých na biodiverzitu.', 'https://placehold.co/600x400', '2024-06-03 00:25:39', 5),
(70, 'Ochrana lesov: Kľúč k udržaniu rovnováhy v prírode', 'Lesy sú jedným z najdôležitejších ekosystémov na Zemi, ktoré poskytujú domov pre množstvo druhov a regulujú klímu.', 'Lesy hrajú kľúčovú úlohu v udržiavaní ekologickej rovnováhy na Zemi. Sú domovom pre nespočetné množstvo druhov rastlín a živočíchov, regulujú vodný cyklus a pôsobia ako zásobárne uhlíka. Ochrana lesov je preto nevyhnutná na zmiernenie klimatických zmien a udržanie biodiverzity. Avšak odlesňovanie, nelegálna ťažba dreva a rozširovanie poľnohospodárskej pôdy predstavujú veľké hrozby pre lesy po celom svete. Organizácie a vlády musia spolupracovať na vytváraní a implementácii politík na ochranu lesov, podporovať udržateľné hospodárenie a zvýšiť povedomie verejnosti o dôležitosti lesov. Investície do zalesňovania a obnova poškodených lesných oblastí sú tiež dôležité kroky na zabezpečenie, že lesy budú naďalej plniť svoje životne dôležité funkcie.', 'https://placehold.co/600x400', '2024-06-03 00:25:39', 5),
(71, 'Plastové znečistenie oceánov: Globálna kríza a možné riešenia', 'Plastové znečistenie predstavuje jednu z najväčších environmentálnych výziev súčasnosti, ohrozuje morský život a zdravie ľudí.', 'Každý rok sa do oceánov dostane milióny ton plastového odpadu, čo má devastujúce účinky na morský život a ekosystémy. Plastové znečistenie ohrozuje mnohé druhy rýb, vtákov a morských cicavcov, ktoré môžu plastové častice považovať za potravu a následne trpieť zdravotnými problémami alebo uhynúť. Mikroplasty sa tiež dostávajú do potravinového reťazca, čo môže mať negatívne dopady na zdravie ľudí. Riešenie tejto krízy vyžaduje globálnu spoluprácu na zníženie výroby plastov, zvýšenie recyklácie a vývoj alternatívnych materiálov. Vlády, firmy a jednotlivci musia pracovať spoločne na vytváraní udržateľných postupov a znížení plastového odpadu, aby sme ochránili naše oceány a ich obyvateľov.', 'https://placehold.co/600x400', '2024-06-03 00:25:39', 5);
INSERT INTO `articles` (`id`, `headline`, `subhead`, `text`, `img_path`, `date`, `category_id`) VALUES
(72, 'Udržateľné poľnohospodárstvo: Cesta k potravinovej bezpečnosti a ochrane prírody', 'Udržateľné poľnohospodárstvo je kľúčom k zabezpečeniu potravinovej bezpečnosti a ochrane prírodných zdrojov pre budúce generácie.', 'Poľnohospodárstvo je základným pilierom našej spoločnosti, ale tradičné poľnohospodárske praktiky môžu mať negatívny dopad na životné prostredie. Udržateľné poľnohospodárstvo sa zameriava na minimalizáciu týchto negatívnych dopadov prostredníctvom využívania ekologických metód, ako sú organické hnojivá, striedanie plodín a integrovaná ochrana proti škodcom. Tieto metódy pomáhajú zlepšovať kvalitu pôdy, znižovať znečistenie vodných zdrojov a podporovať biodiverzitu. Udržateľné poľnohospodárstvo tiež podporuje spravodlivé pracovné podmienky a ekonomickú stabilitu pre farmárov. Prechod na udržateľné poľnohospodárske postupy je nevyhnutný na zabezpečenie potravinovej bezpečnosti a ochranu prírodných zdrojov pre budúce generácie.', '/img/articles/zivot5.jpg', '2024-06-03 00:25:39', 5),
(73, 'Obnoviteľné zdroje energie: Budúcnosť energetiky', 'Obnoviteľné zdroje energie, ako sú slnečná a veterná energia, sú kľúčom k udržateľnej budúcnosti a zníženiu emisií skleníkových plynov.', 'Obnoviteľné zdroje energie predstavujú sľubnú alternatívu k fosílnym palivám a hrajú kľúčovú úlohu v boji proti klimatickým zmenám. Slnečná, veterná, vodná a geotermálna energia sú čisté a nevyčerpateľné zdroje, ktoré môžu nahradiť tradičné formy energie a znížiť emisie skleníkových plynov. Investície do obnoviteľných zdrojov energie nielenže pomáhajú chrániť životné prostredie, ale tiež vytvárajú nové pracovné miesta a podporujú ekonomický rast. Vlády po celom svete prijímajú rôzne opatrenia na podporu vývoja a implementácie obnoviteľných technológií, vrátane daňových stimulov a subvencií. Prechod na obnoviteľné zdroje energie je nevyhnutný na dosiahnutie cieľov Parížskej dohody a zabezpečenie udržateľnej budúcnosti pre všetkých.', '/img/articles/zivot4.jpg', '2024-06-03 00:25:39', 5),
(74, 'Ekológia miest: Ako môžeme vytvoriť udržateľné mestské prostredie', 'Udržateľné mestské prostredie je kľúčom k zlepšeniu kvality života obyvateľov a ochrane životného prostredia.', 'Svetová populácia sa stále viac sťahuje do miest, čo vytvára výzvy pre udržanie ekologickej rovnováhy. Udržateľné mestské prostredie zahŕňa množstvo opatrení na zníženie znečistenia, podporu zelenej infraštruktúry a zlepšenie kvality života obyvateľov. Medzi tieto opatrenia patrí rozvoj verejnej dopravy, podpora cyklistiky a pešej chôdze, výsadba stromov a vytváranie mestských záhrad. Okrem toho je dôležité podporovať energeticky účinné budovy a využívanie obnoviteľných zdrojov energie. Mestské plánovanie by malo byť zamerané na vytváranie inkluzívnych a odolných komunít, ktoré sú pripravené čeliť výzvam klimatických zmien. Vlády, firmy a jednotlivci musia spolupracovať na vytváraní udržateľných miest, ktoré budú poskytovať zdravé a príjemné prostredie pre všetkých obyvateľov.', '/img/articles/zivot3.jpg', '2024-06-03 00:25:39', 5),
(75, 'Globálna ekonomika čelí novým výzvam po pandémii', 'Pandémia COVID-19 mala hlboký dopad na globálnu ekonomiku, ktorá teraz čelí novým výzvam a príležitostiam na obnovu.', 'Pandémia COVID-19 spôsobila bezprecedentné narušenie globálnej ekonomiky, ktoré viedlo k recesii a stratám pracovných miest po celom svete. S ústupom pandémie sa ekonomiky snažia zotaviť a prispôsobiť sa novým podmienkam. Mnohé firmy zistili, že musia inovovať a digitálne transformovať svoje operácie, aby zostali konkurencieschopné. Vládne stimuly a investície do infraštruktúry sú kľúčovými faktormi podporujúcimi ekonomický rast. Okrem toho sa objavujú nové príležitosti v sektore obnoviteľných zdrojov energie a udržateľných technológií. Ekonomické zotavenie však prináša aj výzvy, ako je potreba zaistiť rovnosť príležitostí a riešiť rastúce dlhové bremeno mnohých krajín.', 'https://placehold.co/600x400', '2024-06-03 00:27:00', 6),
(76, 'Finančné trhy zažívajú volatilitu: Investori hľadajú bezpečné prístavy', 'Finančné trhy zažívajú obdobie vysokej volatility, čo núti investorov hľadať bezpečné investície na ochranu svojho kapitálu.', 'Finančné trhy sa v posledných mesiacoch vyznačujú vysokou volatilitou v dôsledku neistoty okolo ekonomického zotavenia, geopolitických napätí a zmien v menovej politike. Investori reagujú na tieto výzvy diverzifikáciou svojich portfólií a hľadaním bezpečných prístavov, ako sú zlato, štátne dlhopisy a stabilné akcie. Centrálne banky po celom svete prijímajú rôzne opatrenia na podporu ekonomiky a udržanie finančnej stability. Analytici varujú, že volatilita môže pokračovať, kým sa nevyriešia kľúčové ekonomické otázky, ako je inflácia a rast úrokových sadzieb. Investori by mali byť pripravení na ďalšie výkyvy a dôkladne zvažovať svoje investičné stratégie.', 'https://placehold.co/600x400', '2024-06-03 00:27:00', 6),
(77, 'Digitálna mena: Budúcnosť finančných transakcií?', 'Digitálne meny sa stávajú čoraz populárnejšími a môžu zmeniť spôsob, akým vykonávame finančné transakcie v budúcnosti.', 'Digitálne meny, ako sú Bitcoin a Ethereum, získavajú na popularite a prispievajú k transformácii finančného sektora. Tieto kryptomeny ponúkajú nové možnosti pre rýchle a bezpečné transakcie bez potreby tradičných bankových inštitúcií. Centrálne banky a vlády po celom svete tiež skúmajú potenciál digitálnych mien a vyvíjajú svoje vlastné digitálne meny (CBDC). Výhody digitálnych mien zahŕňajú zníženie transakčných nákladov, zvýšenie finančnej inklúzie a zlepšenie transparentnosti. Avšak ich rozšírenie prináša aj výzvy, ako je regulácia, ochrana súkromia a prevencia prania špinavých peňazí. Budúcnosť digitálnych mien bude závisieť od ich schopnosti riešiť tieto výzvy a získať dôveru verejnosti.', 'https://placehold.co/600x400', '2024-06-03 00:27:00', 6),
(78, 'Trh práce v postpandemickej ére: Nové trendy a výzvy', 'Trh práce sa mení v dôsledku pandémie, s novými trendmi a výzvami pre zamestnancov a zamestnávateľov.', 'Pandémia COVID-19 zásadne zmenila trh práce, pričom mnohé firmy museli prejsť na diaľkovú prácu a digitalizáciu svojich operácií. Tieto zmeny priniesli nové príležitosti, ale aj výzvy pre zamestnancov a zamestnávateľov. Práca na diaľku sa stala bežnou praxou a mnohé firmy plánujú zachovať flexibilné pracovné usporiadania aj po pandémii. Tento trend však vyvoláva otázky týkajúce sa pracovného prostredia, rovnováhy medzi pracovným a súkromným životom a zabezpečenia kybernetickej bezpečnosti. Okrem toho sa zvyšuje dopyt po digitálnych zručnostiach a odborníkoch na technológie. Firmy musia investovať do vzdelávania a rozvoja svojich zamestnancov, aby zostali konkurencieschopné v meniacom sa pracovnom prostredí.', '/img/articles/eko5.jpg', '2024-06-03 00:27:00', 6),
(79, 'Ekonomická nerovnosť: Výzvy a riešenia pre spravodlivejšiu spoločnosť', 'Ekonomická nerovnosť je jedným z najväčších problémov dnešnej doby, ktorý si vyžaduje komplexné riešenia.', 'Ekonomická nerovnosť je globálnym problémom, ktorý má vážne dopady na sociálnu stabilitu a hospodársky rast. Pandémia COVID-19 tento problém ešte zhoršila, pričom najviac postihla najzraniteľnejšie skupiny obyvateľstva. Riešenie ekonomickej nerovnosti vyžaduje komplexný prístup, ktorý zahŕňa zlepšenie prístupu k vzdelaniu, zdravotnej starostlivosti a pracovným príležitostiam. Vlády môžu prijať politiky na podporu inkluzívneho rastu, ako sú progresívne zdaňovanie, sociálne programy a investície do infraštruktúry. Firmy tiež zohrávajú kľúčovú úlohu tým, že vytvárajú spravodlivé pracovné podmienky a podporujú rozmanitosť a inklúziu. Spoločné úsilie všetkých zainteresovaných strán je nevyhnutné na dosiahnutie spravodlivejšej a udržateľnejšej spoločnosti.', '/img/articles/eko4.jpg', '2024-06-03 00:27:00', 6),
(80, 'Budúcnosť práce: Ako technológie menia pracovné prostredie', 'Technologický pokrok zásadne mení pracovné prostredie a prináša nové výzvy a príležitosti.', 'Technologický pokrok, ako je automatizácia, umelá inteligencia a robotika, zásadne mení pracovné prostredie. Tieto technológie môžu zvýšiť produktivitu a efektivitu, ale zároveň vyvolávajú obavy o budúcnosť pracovných miest. Mnohé rutinné a manuálne práce môžu byť automatizované, čo môže viesť k zániku niektorých pracovných miest. Na druhej strane vznikajú nové pracovné príležitosti v oblastiach, ako sú IT, data science a udržateľné technológie. Firmy a zamestnanci musia byť pripravení na tieto zmeny a investovať do vzdelávania a rozvoja nových zručností. Flexibilita a schopnosť adaptácie budú kľúčové pre úspech v meniacom sa pracovnom prostredí. Vlády a vzdelávacie inštitúcie musia spolupracovať na vytváraní programov, ktoré pomôžu pracovníkom prispôsobiť sa novým požiadavkám trhu práce.', '/img/articles/eko3.jpg', '2024-06-03 00:27:00', 6),
(81, 'Pokroky v liečbe rakoviny: Nové možnosti pre pacientov', 'Vedci dosiahli významný pokrok vo vývoji nových liečebných metód pre pacientov s rakovinou.', 'Vedci nedávno oznámili významné pokroky vo vývoji nových liečebných metód pre pacientov s rakovinou. Tieto nové metódy zahŕňajú pokročilú imunoterapiu, ktorá pomáha telu bojovať proti rakovinovým bunkám prirodzene. Klinické skúšky ukázali sľubné výsledky a pacienti vykazujú výrazné zlepšenie. Tím vedcov tiež pracuje na genetických terapiách, ktoré cieleným spôsobom ničí rakovinové bunky bez poškodenia zdravého tkaniva. Tieto inovácie prinášajú nádej tisícom pacientov a ich rodinám, ktorí čelia tejto závažnej chorobe.', '/img/articles/health6.jpg', '2024-06-03 00:32:21', 1),
(82, 'Politické napätie v Európe: Nové výzvy pre medzinárodnú diplomaciu', 'Európske krajiny čelia rastúcemu politickému napätiu a hľadajú spôsoby, ako zlepšiť vzťahy a spoluprácu.', 'Rastúce politické napätie v Európe prináša nové výzvy pre medzinárodnú diplomaciu. Mnohé krajiny sa snažia nájsť spoločnú reč a zlepšiť vzájomné vzťahy prostredníctvom dialógu a spolupráce. Medzi hlavné otázky patria migrácia, ekonomická stabilita a bezpečnosť. Diplomatické snahy sa zameriavajú na vytváranie trvalých riešení, ktoré by mohli posilniť jednotu a stabilitu v regióne. Vedúci predstavitelia sa pravidelne stretávajú na summitoch, kde diskutujú o týchto kľúčových otázkach a hľadajú konsenzus na medzinárodnej úrovni.', '/img/articles/politika2.jpg', '2024-06-03 00:32:21', 3),
(83, 'Nové technológie menia zdravotníctvo: Robotické operácie a AI', 'Robotické operácie a umelá inteligencia prinášajú revolučné zmeny do zdravotníctva a zlepšujú kvalitu starostlivosti.', 'Zdravotníctvo zažíva revolučné zmeny vďaka novým technológiám, ako sú robotické operácie a umelá inteligencia (AI). Robotické systémy umožňujú chirurgom vykonávať zložité operácie s mimoriadnou presnosťou, čo znižuje riziko komplikácií a urýchľuje zotavenie pacientov. AI sa používa na diagnostiku a liečbu chorôb, kde analyzuje veľké množstvo dát a poskytuje presné predpovede a odporúčania pre liečbu. Tieto technológie zlepšujú kvalitu zdravotnej starostlivosti a prinášajú nové možnosti pre pacientov po celom svete.', '/img/articles/techno2.jpg', '2024-06-03 00:32:21', 4),
(84, 'Ekologické iniciatívy: Mládež sa zapája do ochrany životného prostredia', 'Mladí ľudia po celom svete sa zapájajú do ekologických iniciatív a boja proti klimatickým zmenám.', 'Mladí ľudia po celom svete sa čoraz viac zapájajú do ekologických iniciatív a boja proti klimatickým zmenám. Organizujú protesty, vzdelávacie kampane a dobrovoľnícke aktivity, ktoré zvyšujú povedomie o environmentálnych problémoch a podporujú udržateľné praktiky. Ich úsilie prináša konkrétne výsledky, ako sú zníženie plastového odpadu, ochrana biodiverzity a podpora obnoviteľných zdrojov energie. Mladí aktivisti sú hnacou silou zmeny a ich zapojenie je kľúčové pre zabezpečenie udržateľnej budúcnosti pre všetky generácie.', '/img/articles/zivot2.jpg', '2024-06-03 00:32:21', 5),
(85, 'Ekonomická stabilita po pandémii: Výzvy a príležitosti', 'Pandémia COVID-19 mala hlboký dopad na globálnu ekonomiku, ktorá teraz čelí novým výzvam a príležitostiam na obnovu.', 'Pandémia COVID-19 spôsobila bezprecedentné narušenie globálnej ekonomiky, ktoré viedlo k recesii a stratám pracovných miest po celom svete. S ústupom pandémie sa ekonomiky snažia zotaviť a prispôsobiť sa novým podmienkam. Mnohé firmy zistili, že musia inovovať a digitálne transformovať svoje operácie, aby zostali konkurencieschopné. Vládne stimuly a investície do infraštruktúry sú kľúčovými faktormi podporujúcimi ekonomický rast. Okrem toho sa objavujú nové príležitosti v sektore obnoviteľných zdrojov energie a udržateľných technológií.', '/img/articles/eko2.jpg', '2024-06-03 00:32:21', 6),
(86, 'Veda a výskum: Nové objavy v genetike otvárajú nové možnosti liečby', 'Vedci objavili nové genetické mechanizmy, ktoré by mohli viesť k revolučným metódam liečby rôznych chorôb.', 'Výskum v oblasti genetiky priniesol nové objavy, ktoré by mohli viesť k revolučným metódam liečby rôznych chorôb. Vedci identifikovali konkrétne gény a genetické mechanizmy, ktoré zohrávajú kľúčovú úlohu v rozvoji niektorých ochorení. Tieto objavy otvárajú dvere k vývoju nových genetických terapií, ktoré by mohli cielene zasahovať do týchto procesov a poskytovať účinnú liečbu. Klinické skúšky ukazujú sľubné výsledky a vedci veria, že tieto terapie by mohli priniesť revolučné zmeny v medicíne.', '/img/articles/health7.jpg', '2024-06-03 00:32:21', 1),
(87, 'Politická situácia v Ázii: Rastúce napätie a jeho globálne dôsledky', 'Rastúce politické napätie v Ázii má významné globálne dôsledky a ovplyvňuje medzinárodné vzťahy.', 'Rastúce politické napätie v Ázii prináša významné globálne dôsledky a ovplyvňuje medzinárodné vzťahy. Konflikty medzi krajinami, ako sú Čína a India, majú potenciál destabilizovať región a zasiahnuť globálnu ekonomiku. Medzinárodné spoločenstvo sa snaží nájsť diplomatické riešenia, ktoré by znížili napätie a podporili mier a stabilitu. Diskusie sa zameriavajú na otázky týkajúce sa teritoriálnych sporov, obchodných sankcií a vojenských aktivít. Výsledok týchto diskusií bude mať dlhodobý vplyv na medzinárodné vzťahy a globálnu bezpečnosť.', '/img/articles/politika1.jpg', '2024-06-03 00:32:21', 3),
(88, 'Umelá inteligencia a jej vplyv na trh práce: Príležitosti a výzvy', 'Umelá inteligencia mení trh práce, prináša nové príležitosti, ale aj výzvy pre zamestnancov a zamestnávateľov.', 'Umelá inteligencia (AI) mení trh práce tým, že automatizuje mnohé úlohy a vytvára nové pracovné príležitosti. AI sa využíva v rôznych odvetviach, od výroby cez zdravotníctvo až po služby. Tieto technológie zvyšujú efektivitu a produktivitu, ale zároveň vyvolávajú obavy o budúcnosť pracovných miest. Zamestnanci musia prispôsobiť svoje zručnosti a vzdelanie, aby zostali konkurencieschopní na trhu práce. Firmy musia investovať do školení a rozvoja svojich zamestnancov, aby využili plný potenciál AI. Výzvy spojené s AI zahŕňajú aj etické otázky a reguláciu jej používania.', '/img/articles/techno1.jpg', '2024-06-03 00:32:21', 4),
(89, 'Klimatické zmeny a ich vplyv na globálnu ekonomiku', 'Klimatické zmeny majú významný dopad na globálnu ekonomiku, ovplyvňujú rôzne sektory a prinášajú nové výzvy.', 'Klimatické zmeny majú významný dopad na globálnu ekonomiku, ovplyvňujú rôzne sektory a prinášajú nové výzvy. Zvýšenie teplôt, extrémne poveternostné udalosti a zmeny v zrážkových vzorcoch majú priamy vplyv na poľnohospodárstvo, energetiku, infraštruktúru a zdravotníctvo. Firmy musia prispôsobiť svoje stratégie a investovať do udržateľných technológií a praxí. Vlády musia prijímať politické opatrenia na zmiernenie dopadov klimatických zmien a podporovať výskum a inovácie. Klimatické zmeny predstavujú významnú výzvu, ale aj príležitosť na transformáciu globálnej ekonomiky smerom k udržateľnosti.', '/img/articles/zivot1.jpg', '2024-06-03 00:32:21', 5),
(90, 'Ekonomická politika: Nové prístupy na podporu rastu a stability', 'Ekonomické politiky krajín sa menia v reakcii na globálne výzvy a snažia sa podporiť rast a stabilitu.', 'V reakcii na globálne ekonomické výzvy prijímajú krajiny nové ekonomické politiky, ktoré majú za cieľ podporiť rast a stabilitu. Medzi tieto opatrenia patria fiškálne stimuly, monetárne politiky na podporu likvidity a investície do infraštruktúry a technológií. Cieľom týchto politík je znížiť nezamestnanosť, podporiť podnikanie a zvýšiť konkurencieschopnosť na medzinárodnej úrovni. Vlády tiež zvyšujú svoju spoluprácu na medzinárodných fórach, aby riešili spoločné problémy a koordinovali svoje ekonomické stratégie. Ekonomické politiky budú naďalej hrať kľúčovú úlohu pri riešení výziev, ako sú klimatické zmeny, technologická transformácia a demografické zmeny.', '/img/articles/eko1.jpg', '2024-06-03 00:32:21', 6);

-- --------------------------------------------------------

--
-- Table structure for table `article_category`
--

CREATE TABLE `article_category` (
  `id` int(11) NOT NULL,
  `category` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `article_category`
--

INSERT INTO `article_category` (`id`, `category`) VALUES
(1, 'Zdravie'),
(2, 'Šport'),
(3, 'Politika'),
(4, 'Technológie'),
(5, 'Životné Prostredie'),
(6, 'Ekonomika');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `account`
--
ALTER TABLE `account`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- Indexes for table `article_category`
--
ALTER TABLE `article_category`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `account`
--
ALTER TABLE `account`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=94;

--
-- AUTO_INCREMENT for table `article_category`
--
ALTER TABLE `article_category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `articles`
--
ALTER TABLE `articles`
  ADD CONSTRAINT `articles_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `article_category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
